version: '3.7'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - default
  postgresdb:
    container_name: postgresdb
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=postgresdb
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=weaponshop
    networks:
      - default
